module.exports = [
   `Kingdom's collapse, Regional rulers emerge, Chaos and rebirth.`,
   `Hyksos invaders, Foreign rule disrupts Egypt, Native pride endures.`,
   `Decentralized rule, Libyan and Nubian kings, Egypt's sovereignty.`,
   `Narmer unifies, First Pharaoh, foundation laid, Egypt's dawn begins.`,
   `Old Kingdom's grandeur, Pyramids, eternal tombs, Pharaohs' immortal reign.`,
   `Middle Kingdom's strength, Reunited land, progress, Prosperity restored.`,
   `New Kingdom's glory, Pharaohs mighty, empire expands, Ancient Egypt's zenith.`,
   `Late Period's decline, Foreign rule, Egypt's struggles, End of native reign.`,
   `Ptolemaic line, Greek rulers, Hellenistic blend, Cleopatra's reign shines.`,
   `Rosetta's triumph, Key to unlocking the past, Deciphering time's script.`,
   `Sphinx's watchful gaze, Guardian of Egypt's secrets, Enigma of time.`,
   `Nefertiti's grace, Egypt's radiant queen shines, Beauty immortal.`,
   `Amarna's allure, Nefertiti, royal muse, Ancient art's marvel.`,
   `Egypt's pharaohs rule, Mighty pyramids stand tall, Monuments of power.`,
   `Pyramids of old, Testament to ancient might, Mysteries unfold.`,
   `Egyptian pharaohs, Rulers of a bygone era, Legacy remains.`,
   `Akhenaten's reign, Sun-drenched Amarna's glory, Pharaoh's divine light.`,
   `Rosetta's enigma, Key to deciphering past, Language resurrected.`,
   `Akhenaten's reign, Sun god's worship embraced, Amarna's golden age.`,
   `Rosetta Stone's code, Key to deciphering past, Egypt's ancient script.`,
   `Osiris, the judge, God of afterlife and death, Eternal rebirth.`,
   `Isis, divine queen, Goddess of magic and love, Protector and wife.`,
  	`Pyramids rise high, Ancient engineering feats, Wonders of mankind.`,
`Nefertari's grace, Queen of Ramses' love and pride, Beauty revered.`,
   `Egypt's weakening, New Kingdom's waning glory, Pharaohs' diminished reign.`,
   `Ramses the Great, Pharaoh's mighty reign and might, Egypt's golden age.`,
   `The Great Sphinx stands tall, Guardian of ancient Egypt, Mysteries enshrined.`,
   `Giza's Pyramids, Majestic tombs of pharaohs, Testament to power.`,
   `The Temple of Karnak, Sacred complex of gods, Colossal architecture.`,
   `Luxor's Avenue of Sphinxes, A procession of legends, Guarding temples' secrets.`,
   `The Valley of the Kings, Hidden tombs of pharaohs, Treasures of the past.`,
   `The Temple of Abu Simbel, Carved rock marvels the sun, Ramesses' grand tribute.`,
   `The Temple of Hatshepsut, Queen's divine sanctuary, Architectural feat.`,
   `The Temple of Horus, Edfu's falcon god revered, Pristine ancient art.`,
   `The Temple of Isis, Philae's island sanctuary, Goddess of love and magic.`,
   `Abu Simbel's grace, Carved in Nubian sandstone, Pharaohs' eternal gaze.`,
   `Sun's rays penetrate, Illuminating the gods, Abu Simbel's awe.`,
   `The Temple of Kom Ombo, Dual deities' domain, Crocodile and falcon.`,
   `Nefertari's tomb, Exquisite paintings adorn, Queen's eternal rest.`,
   `Ramses' warrior, Battlefield's fierce commander, Victories resound.`,
   `Nefertari's charm, Queen of charm and elegance, Radiant presence.`,
   `Ramses' temples rise, Monuments to his glory, Architecture grand.`,
   `Nefertari's wisdom, Queen's counsel sought and valued, Influence profound.`,
   `Ramses' legacy, Builder of grand monuments, History's testament.`,
   `Nefertari's love, Devoted to Ramses' heart, Unbreakable bond.`,
   `Together they ruled, Nefertari and Ramses, Egypt's eternal couple.`,
   `Ra, the sun god, Radiant light and power, Day's eternal guide.`,
   `Horus, falcon god, Sky guardian and avenger, Pharaoh's noble guide.`,
   `Bastet, lioness, Goddess of joy and warfare, Feline protector.`,
   `Thoth, the wise scribe, God of wisdom and knowledge, Record keeper true.`,
   `Amarna's sunlight, Pharaoh Akhenaten's reign, A unique era.`,
   `Nefertiti's grace, Beautiful queen by his side, Symbol of Amarna.`,
   `Aten's radiant, Sole god worshiped, supreme light, Amarna's faith.`,
   `Artistic revolution, Naturalistic beauty, Amarna's legacy.`,
   `Royal capital, Akhetaten's city grand, Amarna's domain.`,
   `Religious fervor, Traditional gods defied, Amarna's rebellion.`,
   `Amarna letters, Correspondence with the world, Insights into time.`,
   `Cultural shift, Pharaoh's artistic vision, Amarna's transformation.`,
   `Amidst the ruins, Whispers of a forgotten age, Amarna's secrets.`,
   `Archaeologists, Unearthing Amarna's past, Unveiling its tales.`,
   `Anubis, jackal, Guardian of the underworld, Weigher of the heart.`,
   `Sekhmet, lioness, Goddess of war and healing, Fierce and loving force.`,
   `Ma'at, balance's scale, Goddess of truth and justice, Order's divine rule.`,
   `Icon of power, Nefertiti, Pharaoh's wife, Regal authority.`,
   `Heretic's consort, Nefertiti's rebel heart, Amun's defiance.`,
   `Nile's golden queen, Nefertiti, Egypt's pride, Her legacy reigns.`,
   `Nefertiti's charm, The beautiful one has come, Egypt's radiant queen.`,
   `Akhenaten, king, Sun's radiant pharaoh shines, Amarna's bright dream.`,
   `Amun's heretic, Akhenaten defies gods, Aton's light embraced.`,
   `Monotheistic reign, Akhenaten's radical, Egypt's sun-drenched path.`,
   `Amarna's city, Akhenaten's grand vision, Art and worship blend.`,
   `Father of Tutankhamun, Akhenaten's lineage, Legacy's golden thread.`,
   `Golden sands reveal, Pharaohs' tombs and mystic lore, Egypt's ancient tale.`,
   `Scrolls of papyrus, Hieroglyphs that guard secrets, Lost words, ancient grace.`,
   `Hieroglyphic code, Sacred symbols tell their tales, Cryptic wisdom shared.`,
   `Pyramids of sand, Whispering desert secrets, Egypt's sandy shroud.`,
   `Hatshepsut, queen's might, Egypt's female pharaoh bold, Power she wields strong.`,
   `Valley of the Kings, Hatshepsut's temple of grace, Monumental grace.`,
   `Pioneering rule, Hatshepsut, female pharaoh, Ancient gender shift.`,
   `Maatkare's legacy, Hatshepsut's divine reign, Wisdom guides her path.`,
   `Trade routes flourish, Hatshepsut's prosperous rule, Egypt's golden age.`,
   `Papyrus scrolls unfurl, Ink dances with ancient words, Egyptian knowledge.`,
   `Pharaoh's golden mask, Tutankhamun's splendor shines, Egypt's royal grace.`,
   `Sacred Nile's embrace, Life's eternal river flows, Egypt's timeless gift.`,
   `Valley of the Kings, Tombs hold pharaohs' regal sleep, Egypt's royal rest.`,
   `Giza's pyramids, Silent testament to man, Enduring marvels.`,
   `Rosetta's key unlocks, Lost scripts of ancient wisdom, Egypt's linguistic bridge.`,
   `Hieroglyphic dance, Ink on papyrus whispers, Egypt's written lore.`,
   `Nile's gentle caress, Life springs forth from ancient sands, Egypt's timeless gift.`,
   `Pyramids towering, Mysteries sealed within stones, Egypt's ancient crown.`,
   `Cleopatra's grace, Ptolemaic Queen of Nile, Egypt's last allure.`,
   `Nile's life-giving flow, Fertile delta, ancient gift, Egypt's heartbeat strong.`,
   `Temple of Karnak, Monument to gods and kings, Divine majesty.`,
   `Ptolemaic rule, Greek pharaohs on Egyptian soil, Cultural fusion.`,
   `Moses, chosen leader, Israelites' exodus, Miracles unfold.`,
   `Plagues upon Egypt, Israelites' liberation, Divine intervention.`,
   `Red Sea's parting waves, Israelites cross to freedom, Egypt's hold shattered.`,
   `Book of the Dead's scrolls, Guide to afterlife's journey, Ancient wisdom shared.`,
   `Amarna's embrace, Akhenaten's vision blooms, Sun's radiant grace.`,
   `Narmer's reign begins, Unifying Upper and Lower, Egypt's grand debut.`,
   `Hatshepsut's power, Female pharaoh's golden age, Bold queen's legacy.`,
   `Nubian rulers, Egypt's Kushite kings ascend, Cultural exchange.`,
   `Persian dominion, Foreign rule grips Egypt's land, Freedom yet to come.`,
   `Macedonian kings, Ptolemaic dynasty's reign, Cleopatra's fame.`,
   `Khasekhemwy's rule, Continuing the foundation, Egypt's legacy.`,
   `Djoser's pyramid, Step Pyramid's majestic rise, Architectural feat.`,
   `Khufu's Great Pyramid, Icon of ancient power, Monumental might.`,
   `Solar temples shine, Sun-worshipping pharaohs' reign, Cultural blossoms.`,
   `Teti's pyramid, Old Kingdom's final chapters, Dynasty's decline.`,
   `Mentuhotep's rule, Reunification's strength, Middle Kingdom's dawn.`,
   `Senusret's splendor, Golden age of art and trade, Middle Kingdom's peak.`,
   `Uncertain reigns, Fragmented power and turmoil, Dynasty's struggles.`,
   `Thebes' rise to might, Ahmose's expulsion of foes, New Kingdom's triumph.`,
   `Short-lived rulers' reign, Uncertainty and unrest, Chaos in Egypt.`,
   `Library of books, Alexandria's treasure trove, Knowledge revered.`,
   `Weak pharaohs in charge, Fragmented rule and decline, Egypt's waning power.`,
   `Herakleopolis, Centralized authority, Pharaohs restore order.`,
   `Nomarchs' influence, Regional governors' rule, Egypt's shifting power.`,
   `Influx of foreigners, Hyksos ascendancy, Egypt's foreign rule.`,
   `Hyksos rulers' sway, Eastern Delta's domination, Egypt's foreign yoke.`,
   `Short-lived reigns emerge, Decline and division persist, Egypt's troubled times.`,
   `Akhenaten's reign, Amarna's radical shift, Aton's radiant light.`,
   `Ramses the Great's might, Temple builder, warrior, Egypt's golden age.`,
   `Ramses III's rule, Defender against invaders, Egypt's final stand.`,
   `Theban High Priests rise, Power in religious hands, Egypt's theocratic phase.`,
   `Libyan kings ascend, Shoshenq I, rule extended, Egypt's foreign touch.`,
   `Kings of mixed descent, Political chaos ensues, Dynasty's short reign.`,
   `Nubian pharaohs rule, Piye, Taharqa's might shines, Egypt's Kushite kings.`,
   `Assyrian conquest, Nubian kings pushed aside, Egypt's foreign yoke.`,
   `Saite kings restore, Egypt's independence regained, Revival in the Nile.`,
   `Ptolemaic rule, Egypt's pharaohs of Greek blood, Cleopatra's reign.`,




];


