module.exports = [
   `Mighty horns arise, Symbols of sacred power, Consecration's mark.`,
  `Crowned with spiral horns, Divine embodiment shines, Strength and majesty.`,
  `Ancient ritual, Horns of consecration sound, Awe and reverence.`,
  `Horns touch the heavens, Bridge between realms of mortals, And gods above.`,
  `Carved from sacred wood, Horns of consecration gleam, Artistry divine.`,
  `Through sacred rituals, Horns of consecration bless, Bridging earthly realms.`,
  `Horns crown the deity, Divinity manifested, Anointed with grace.`,
  `Echoes of ancient, Horns resonate with reverence, Sanctified echoes.`,
  `Beasts with mighty horns, Symbols of divine power, Protectors revered.`,
  `Horns of sacred bull, Strength and virility proclaimed, Sacred energy.`,
  `Blessed horns of consecration, Anointing the chosen ones, Divine intervention.`,
  `Horns, symbols of might, Bestowed upon sacred few, Divine inheritance.`,
  `Charged with sacred force, Horns of consecration bring, Blessings from above.`,
  `Curved horns, vessels pure, Consecrated offerings, Sanctified blessings.`,
  `Mystic horns resound, Echoes of ancient power, Ancestral wisdom.`,
  `Divine bovine horns, Consecrated gifts bestowed, Grace from higher realms.`,
  `Horns pierce the heavens, Carrying prayers to the gods, Seeking divine grace.`,
  `Hallowed horns of might, Crowned heads with sacred essence, Divine sovereignty.`,
  `Chalice of blessings, Horns of consecration pour, Divine elixir.`,
  `Horns, sacred symbols, Anointed with sacred oil, Consecrated grace.`,
  `Blessed horns proclaim, Divine favor bestowed upon, Chosen mortal souls.`,
  `Horns, conduits of power, Sanctified and revered, Ancient connection.`,
  `Through the sacred horns, Energy flows, blessings pour, Channel of divine.`,
  `Horns of consecration, Mark of divine favor, Anointed with grace.`,
  `Horns, ancient beacons, Guiding mortals to the divine, Sacred compass points.`,
  `Celestial horns, Consecrated to the gods, Transcendent blessings.`,
  `Horns herald new dawn, Awakening divine grace, Consecrated light.`,
  `Sacred horns entwined, Symbol of unity divine, Blessed union's bond.`,
  `Horns, ancient symbols, Consecrated embodiment, Divinity's mark.`,
` Bull of Marathon, Wild and raging, tamed by strength, Theseus shows his might.`,
` Periphetes, cruel, Club wielded with brutal force, Theseus brings him down.`,
` Savage sow of Crommyon, Defeated with cunning skill, Theseus claims his triumph.`,
` Procrustes, the stretcher, His bed becomes his own snare, Theseus ends his reign.`,
` Sinis, the pine bender, Cast down from his own device, Theseus brings justice.`,
` Minotaur, fearsome, Labyrinth's maze navigated, Theseus slays the beast.`,
` Lion's fearsome roar, Heracles, strength unmatched, First labor conquered.`,
  `Hydra's serpentine, Regenerating heads attacked, Second labor won..`,
  `Ceryneian hind, Golden horns glint in the wild, Swift pursuit begins..`,
  `Erymanthian boar, Rampaging through the forests, Tamed by Heracles..`,
  `Augean stables, Rivers redirected, cleaned, Fifth labor achieved..`,
  `Stymphalian birds, Feathers sharp as arrows fly, Heracles aims true.`,
  `Cretan bull subdued, Mighty strength tames the beast, Seventh labor done..`,
  `Horses of Diomedes, Ferocious and wild, Captured by Heracles..`,
  `Girdle of Hippolyta, Queen's prized possession secured, Ninth labor complete..`,
  `Cattle of Geryon, Three-headed guardian slain, Final task conquered..`,
   `Golden apples steal, Guarded by Hesperides, Eleventh labor faced.`,
   `Cerberus, hound fierce, Guardian of the underworld, Heracles prevails.`,
   `With these twelve labors, Heracles earned his renown, A hero's legacy.`,
`Olympus awaits, Gods and heroes, myths untold, Greece's timeless flame.`,
   `Troy's epic battle, Hector's honor, Achilles' rage, Myth and history.`,
   `Grecian olive groves, Sacred trees of peace and strength, Homer's fertile muse.`,
   `Bellerophon, brave, Mounted on Pegasus' back, Heroic quests await.`,
   `Chimera's slayer, With spear and divine creature, Fame and glory earned.`,
   `Tamed the winged horse, Rode through the sky with valor, Adventures untold.`,
   `Zeus' favor won, Gifted with Pegasus, bold, Fate's chosen hero.`,
   `Bellerophon, skilled, A warrior of great might, Legends shall endure.`,
   `Greek philosophers, Inquiring minds seeking truth, Classical wisdom.`,
   `Tales of ancient Troy, Heroes clash in epic wars, Legends come alive.`,
   `Greek democracy, Birthplace of civic virtue, Voices of the free.`,
   `Athens' marble crown, Philosophy's birthplace thrives, Wisdom's sacred ground.`,
   `Zeus, king of the gods, Thunderbolts, sovereignty's might, Olympus bows low.`,
   `Hera, queen divine, Protector of marriage's bond, Ever watchful eye.`,
   `Poseidon, sea's lord, Trident wields, waves obey, Empire beneath waves.`,
   `Demeter, earth's life, Bountiful harvests bestowed, Nature's motherly care.`,
   `Mycenae's downfall, Palaces razed to the ground, End of Mycenaean.`,
   `Ares, god of war, Battle's fury in his veins, Warriors heed his call.`,
   `Dorian invasion, Greek Dark Age's emergence, Societies transformed.`,
   `Regional powers, City-states rise from the ruins, Greek world reshaped.`,
   `Athena, wisdom's grace, Strategist, noble counsel, Shield of intellect.`,
   `Apollo, the sun, Music, prophecy, healing, Radiant arts thrive.`,
   `Artemis, moon's huntress, Bow and arrow, swift pursuit, Nature's sacred guard.`,
  `Greek philosophers, Seekers of truth and knowledge, Wisdom for all ages.`,
`Troy's epic saga, Heroes clash in battle's heat, Ancient legends told.`,
   `Greek democracy, Athens' birthplace of freedom, Citizens' voice heard.`,
   `Minoan civilization, Crete's ancient marvels, Lost world of mystery.`,
   `Knossos palace grand, Maze of corridors and rooms, Labyrinthine charm.`,
   `Bull-leaping frescoes, Minoan athleticism, Graceful acrobats.`,
   `Phaistos Disc's enigma, Undeciphered script remains, Language locked in time.`,
   `Minoan ships sail, Traders of the Mediterranean, Maritime prowess.`,
   `Goddess of Snake, Symbol of Minoan power, Protectress divine.`,
   `Throne Room's vibrant art, Minoan frescoes enchant, Palace's painted tales.`,
   `Minoan ceramics, Intricate patterns and motifs, Artisans' mastery.`,
   `Tylissos' stone houses, Ancient Minoan village, Ruins tell their story.`,
   `Minoan women's role, Goddess worship and power, Matrilineal sway.`,
   `Minoan decline, Natural disasters or strife, Civilization's end.`,
   `Hephaestus, forge's fire, Craftsman's skill, divine creations, Beauty shaped with hands.`,
   `Aphrodite, love's queen, Goddess of desire and charm, Hearts entwined with grace.`,
   `Dionysus, divine, Wine and revelry's delight, Ecstasy unleashed.`,
   `Hermes, swift of foot, Messenger of gods and men, Guide through realms unseen.`,
   `Aphrodite's laughter, Whispers of passion's embrace, Love's eternal flame.`,
   `Aphrodite's gaze, Enchanting allure bestowed, Beauty's sweet embrace.`,
   `Aphrodite's touch, Heart's desires set ablaze, Passion's fiery dance.`,
   `Olympic glory, Ancient games, immortal flame, Athletic tribute.`,
   `Delicate frescoes, Vivid colors on the wall, Minoan beauty.`,
   `Mighty Herakles, Nemean lion tamed by strength, Legend lives through time.`,
   `Twelve labors faced, Herakles, hero's triumph, Zeus' mortal son.`,
   `Club and lion's pelt, Herakles, symbol of might, Champion of gods.`,
   `Hera's wrath endured, Herakles, divine trials, Immortality earned.`,
   `Herakles, demigod, Strength unmatched, hero renowned, Tales of valor sung.`,
   `Mycenaean walls, Cyclopean strength endures, Greek fortress of old.`,
   `Greek tragedy's stage, Masked emotions, tragic fates, Drama's immortal.`,
   `Alexander's march, Conquest echoes through the ages, Hellenistic dreams.`,
   `Minoan echoes, Knossos whispers ancient tales, Crete's forgotten lore.`,
   `Delphi's sacred peak, Oracle's prophetic voice, Wisdom echoes still.`,
   `Acropolis stands tall, Parthenon's majestic grace, Ancient homage paid.`,
   `Aegean's blue embrace, Cycladic mysteries unfold, Greece's island tales.`,
   `Olive branch extends, Symbol of peace and wisdom, Greece's sacred tree.`,
   `Spartan discipline, Warrior code, iron will, Ancient valor's flame.`,
   `Oracle's whispers, Delphi's cryptic prophecies, Future's veiled secrets.`,
   `Muses' gentle touch, Inspiration's golden thread, Artists' guiding light.`,
   `Homer's epic verse, Iliad and Odyssey, Tales of heroes sung.`,
   `Greek philosophers, Sages of profound wisdom, Enlightening minds.`,
   `Olympian heights, Gods and goddesses preside, Mount Olympus' realm.`,
   `Trojan walls besieged, Achilles' wrath consumes all, War echoes through time.`,
   `Helen's face launches, Thousand ships to Trojan shore, Epic conflict born.`,
   `Troy's tragic fate sealed, Wooden horse hides Greek warriors, Deception conquers.`,
   `Ancient Greek's grace, Language of gods and scholars, Wisdom woven deep.`,
   `Olympian tales, Ancient Greek mythology, Legends never fade.`,
   `Greek philosophers, Socrates, Plato, and more, Enlightenment's spark.`,
   `Hellenic culture, Arts and sciences flourish, Ancient Greece's gift.`,
   `Athenian spirit, Democracy's birthplace, Ancient Greek ideals.`,
   `Heroes clash in dust, Hector's valor shines bright, Troy's defenders brave.`,
   `Iliad's epic tale, Gods and mortals entwined, Trojan War unfolds.`,
   `Priam's plea resounds, Hector's noble sacrifice, Troy's heart breaks in loss.`,
   `Achilles' heel strikes, Fated arrow finds its mark, Greek champion falls.`,
   `Trojan warriors, Defending their ancient walls, Courage in the face.`,
   `Helen's haunting face, Beauty's spark ignites the flames, War of love and pride.`,
   `Odysseus schemes, Crafty mind weaves Trojan fall, Homebound hero's quest.`,
   `Helenus, seer, Troy's prophetic voice guides, Wisdom from within.`,
   `Cursed with foresight's gift, Cassandra's voice cries in vain, Tragedy unfolds.`,
   `Cassandra's visions, Prophecies of tragic fate, Unheeded warnings.`,
   `Sappho's words of love, Lyric poetry's sweet grace, Melodies of heart.`,
   `Lesbos' gifted muse, Sappho's verses touch the soul, Passion intertwines.`,
   `Love's flame in her words, Sappho's longing, desire's cry, Aching hearts embrace.`,
   `Sappho's tender touch, Lines of desire and beauty, Eros' gentle fire.`,
   `Whispers of Sappho, Ancient echoes of her voice, Immortal poetess.`,
   `Andromache's grief, Hector's fallen, Troy in flames, Heartache's eternal.`,
   `Widowed in the war, Andromache, strong and brave, Love's memory burns.`,
   `Hector's faithful wife, Andromache's strength endures, Mother, warrior's muse.`,
   `Hypatia's brilliance, Astronomer and scholar, Alexandria's star.`,
   `Philosopher's mind, Hypatia's wisdom revered, Intellectual light.`,
   `Inscribed in her name, Mathematical insights, Hypatia's legacy.`,
   `Defying confines, Hypatia challenges norms, Trailblazer of thought.`,
   `Tragic fate befalls, Hypatia's martyrdom, Science weeps in loss.`,
   `Aspasia's allure, Athenian beauty and wit, Pericles' true muse.`,
   `Socrates' confidant, Aspasia's wisdom revered, Intellect's embrace.`,
   `Political mind, Aspasia's influence blooms, Athens' guiding light.`,
   `Rhetoric's enchantress, Aspasia's words enthrall, Power in her voice.`,
   `Resilient and bold, Aspasia challenges norms, Feminine power shines.`,
   `Gorgo, Spartan queen, Wise counsel and strength of will, Courageous and fierce.`,
   `Leonidas' wife, Gorgo, backbone of Sparta, Her spirit unyielding.`,
   `Euripides, bold, Greek tragedian renowned, Dramatic rebel.`,
   `Medea's fury, Vengeful mother's chilling cry, Children pay the price.`,
   `The Trojan Women, Victims of war's cruel fate, Suffering unveiled.`,
   `Electra's anguish, Avenging father's murder, Darkness seeks justice.`,
   `The Bacchae's dance, Dionysus's wild ecstasy, Civilization torn.`,
   `Hecuba's lament, Queen's sorrow, lost kingdom's grief, Troy's tragic downfall.`,
   `The Women of Troy, Voice of silenced captives, weep, Broken hearts speak out.`,
   `Alcestis, pure love, Sacrifice for husband's life, Death's triumph undone.`,
   `Andromache, slave, Hector's widow, Trojan's plight, Surviving tragedy.`,
   `Iphigenia, Sacrificial lamb for war, Family's pain revealed.`,
   `Euripides, voice, Human flaws and sorrows laid, Tragedy's essence.`,
   `Aeschylus, profound, Father of Greek tragedy, Myths woven on stage.`,
   `Prometheus bound, Titan's defiance unleashed, Firebearer's plight.`,
   `Oresteia's tale, Blood-stained House of Atreus, Justice seeks its course.`,
   `Persians mourn their loss, Grief of empire defeated, War's aftermath felt.`,
   `Agamemnon's fate, Sacrifice of Iphigenia, Troy's price paid in blood.`,
   `Aeschylus, genius, Innovator of drama, His words echo still.`,
   `Intrigue and power, Gorgo's influence unveiled, Politics at play.`,
   `Protector of Sparta, Gorgo's devotion unwavering, Heart beats for her land.`,
   `Aeschylus, grandeur, Tragic visions shape the stage, Gods and mortals clash.`,
   `Sophocles, wisdom, Oedipus, Antigone, Fate's cruel designs.`,
   `Euripides, bold, Passion's turmoil, sorrows deep, Human hearts exposed.`,
   `Sophocles, master, Tragic visions brought to life, Insight in his words.`,
   `Oedipus Rex, Fateful prophecy fulfilled, Blindness brings insight.`,
   `Antigone's plight, Defiance of unjust law, Morality upheld.`,
   `Electra's sorrow, Vengeance drives her desperate quest, Family's tragic end.`,
   `Ajax, noble yet, Madness claims his valiant soul, War's toll takes its toll.`,
   `Sophocles, timeless, Human drama's eternal, His genius endures.`,
   `Greek tragedies, Cathartic purging of souls, Emotions laid bare.`,
   `Theatre of pain, Tragic heroes meet their end, Lessons carved in stone.`,
   `Gorgo's legacy, Respected queen of warriors, Spartan legend lives.`,
   `Artemisia the queen, Fearless ruler of Halicarnassus, Seafaring strength.`,
   `Persian alliance, Artemisia's loyalty, Xerxes' trusted advisor.`,
   `Sailed the Aegean, Artemisia, skilled tactician, Naval prowess known.`,
   `Dressed as Artemis, Warrior queen led the charge, Bravery personified.`,
   `Immortalized in tales, Artemisia, legend's embrace, Queen of the seas.`,
   `Anyte, poetess, Verse weaves nature's harmonies, Ancient muse's voice.`,
   `Epigrammatist, Anyte's words etched in stone, Elegance in brevity.`,
   `Nature's lyricist, Anyte's pen sings of life, Flora and fauna's praise.`,
   `From Tegea's land, Anyte's poetry blooms, Honoring the world.`,
   `Unveiling beauty, Anyte's verses enchant, Her legacy thrives.`,
   `Olympias, queen, Mother of Alexander's might, Power flows through blood.`,
   `Oracle's daughter, Olympias, mystic soul, Divine prophecies.`,
   `Snake-wreathed priestess, Olympias, Zeus' consort, Sacred union forged.`,
   `Macedon's lioness, Olympias' fierce spirit, Defender of honor.`,
   `Legend in her wake, Olympias, history's thread, Queen of Macedon.`,
   `Lysimache, queen, Daughter of Thracian realm, Strength flows in her veins.`,
   `Strategist's mind, Lysimache's cunning ways, Tactician's prowess.`,
   `Thrace's ruler fair, Lysimache commands with grace, Courageous and just.`,
   `Amazons' heritage, Lysimache's warrior spirit, Amazon queen's pride.`,
   `Bold and resolute, Lysimache's reign prevails, Thracian kingdom's pride.`,
   `Amazon warriors, Fierce and untamed in battle, Legends carved in stone.`,
   `Matriarchal might, Amazons' empowered rule, Gender defying.`,
   `Bow-wielding archers, Amazons' deadly precision, Arrows seek their mark.`,
   `Brave and unconstrained, Amazons roam untamed lands, Freedom in their hearts.`,
   `Mythical allure, Amazons' strength and beauty, Enigma of old.`,
   `Daring Amazon, Defiant against all odds, Courage never wanes.`,
   `At Themyscira, Amazons' sacred haven, Island of power.`,
   `Sisterhood bonded, Amazons stand united, Unity their shield.`,
   `Tales of bravery, Amazons' legacy told, Inspiring generations.`,
   `Amazon queens lead, Wisdom guides their noble realm, Eternal glory.`,
   `Hellenistic dawn, Alexander's empire blooms, Greek culture spreads wide.`,
   `Hellenistic art, Realism and emotion, Beauty in marble.`,
   `Hellenistic kings, Warlords of fragmented lands, Power struggles fierce.`,
   `Epicurean thought, Seeking pleasure and content, Philosophy's path.`,
   `Stoic teachings guide, Inner virtue, harmony, Zenith of wisdom.`,
   `Cosmopolitan, Greek influence far and wide, Cultural melting pot.`,
   `Hellenistic age, Innovation and progress, Science and learning.`,
   `Greek cities thrive, New urban centers emerge, Trade and prosperity.`,
   `Legacy endures, Hellenistic world transformed, Greek imprint remains.`,
   `Greek city-states fade, Hellenistic era dawns, Kingdoms rise and fall.`,
   `Macedonian might, Under Alexander's reign, Conquering the East.`,
   `Seleucid Empire, Greeks ruling distant lands, Eastward expansion.`,
   `Pergamon's splendor, Library and grand altar, Seat of learning thrives.`,
   `Gymnasiums flourish, Intellectual pursuits, Philosophy's realm.`,
   `Hellenistic art, Dramatic emotion flows, Pathos in marble.`,
   `Sculptures come alive, Dynamic poses, movement, Capturing essence.`,
   `Koine Greek spreads wide, Unified language of trade, Connecting the world.`,
   `Athens in decline, Cultural influence wanes, New powers emerge.`,
   `Philosophy's heirs, Stoics, Epicureans, more, Ancient wisdom lives on.`,

];


