module.exports = [
   `Palmyra's arches, Carved in sandstone, time-worn grace, Ancient trade routes.`,
   `Sargon the Great's reign, Akkadian empire's rise, Founder of dynasties.`,
   `Akkadian language, Cuneiform script's ancient form, Words etched in clay.`,
   `City of Akkad, Cultural hub and center, Trade and innovation.`,
   `Mesopotamia, Cradle of ancient empires, Civilization.`,
   `Akkadian warriors, Skilled in the art of warfare, Strength forged in battle.`,
   `Sumerian heritage, Akkadians build upon, Legacy's fusion.`,
   `Mesopotamia's cradle, Sumerians' first writing, Civilization's dawn.`,
 `Cuneiform secrets, Clay tablets, ancient wisdom, Mesopotamia's gift.`,
   `Enki, wise and kind, God of water and wisdom, Creator of life.`,
   `Inanna, goddess, Queen of heaven and earth's love, Beauty and power.`,
   `Hittite Empire fades, Powerful Anatolian realm, Vanished from history.`,
   `Marduk, warrior, Slayer of Tiamat, fierce king, Babylon's protector.`,
   `Hittites, mighty realm, Anatolian power, Forgotten empire.`,
   `Hattusa's walls stand, Capital of Hittite kings, Fortress of strength.`,
   `Hittite chariots, Warriors ride to battle, Bronze-clad and fierce.`,
   `Bogazköy's secrets, Tablets inscribed with history, Hittite words endure.`,
   `Persian Empire vast, Cyrus the Great's legacy, Mighty conquerors.`,
   `Persepolis shines, Achaemenid capital, Splendor of Persia.`,
   `Darius the Great, Persian king of vision, Empire's architect.`,
   `Cyrus' Cylinder, First human rights document, Tolerance proclaimed.`,
   `Xerxes' invasion, Greece's valiant defense, Thermopylae's stand.`,
   `Satraps rule provinces, Persian governance, Cultural diversity.`,
   `Persian gardens bloom, Paradise on Earth's delight, Nature's harmony.`,
   `Royal Road stretches, Ancient trade route's pathway, Connections forged.`,
   `Zoroastrian faith, Ahura Mazda's teachings, Light against darkness.`,
   `Persepolis ruins, Whispers of Persian glory, Ancient echoes heard.`,
   `Lion Gate's grand entrance, Breathtaking Hittite art, Roaring guardians.`,
   `Hittite laws declared, Code of justice and order, Fairness upheld.`,
   `Suppiluliuma's reign, Hittite glory restored, Empire expands.`,
   `Storm god's wrath unleashed, Tarhunzas' thunderous might, Hittite deity.`,
   `Hittite diplomacy, Treaties forged and upheld, Peaceful alliances.`,
   `Hittite craftsmanship, Metalwork and artistry, Culture's vibrant mark.`,
   `Arzawa's conquest, Hittite expansion's reach, Territories claimed.`,
   `Hittite charioteers, Skilled warriors in battle, Victory assured.`,
   `Hittite goddess, Hepatu, Protector of the kingdom, Divine guidance sought.`,
   `Iron Age Hittites, Technological prowess, Advancements revered.`,
   `Tawagalawa's plea, Letter to Egyptian pharaoh, Diplomatic plea.`,
   `Hittite heritage, Anatolia's ancient pride, Legacy preserved.`,
   `The Hanging Gardens, Babylon's lush wonderland, Nature defying.`,
   `Ziggurat of Ur, Mesopotamia's grand pride, Stairway to the gods.`,
   `Persepolis shines, Achaemenid legacy, Persian majesty.`,
   `Etemenanki's tower, Babylon's sacred ascent, Reaching for the skies.`,
   `Ctesiphon's arches, Parthian grandeur remains, Ancient splendor lives.`,
   `The Ishtar Gate stands, Babylon's magnificent, Lion's guardian roar.`,
   `Taq-e Bostan's art, Sasanian rock reliefs, Kings' eternal mark.`,
   `Nimrud's ancient city, Assyrian empire's heart, Ruins whisper tales.`,
   `Apadana Palace, Darius' regal abode, Persian opulence.`,
   `Hatra's fortress strong, Parthian defensive might, Ancient walls endure.`,
   `Ishtar, goddess, Love and fertility's joy, Warrior and queen.`,
   `Nergal, god of death, Terrifying and relentless, Ruler of the underworld.`,
   `Shamash, radiant, Sun god, dispenser of justice, Light in darkness.`,
   `Ninurta, mighty, God of agriculture, war, Champion of the land.`,
   `Cradle of knowledge, Mesopotamia's glory, Civilization.`,
   `Tigris and Euphrates, Rivers of ancient wisdom, Life's arteries flow.`,
   `Ziggurats so high, Stairways to the divine realm, Seekers of heaven.`,
   `Hammurabi's code, Justice carved in stone tablets, Law for all to see.`,
   `Epic of Gilgamesh, Tales of hero's quest and love, Ancient echoes heard.`,
   `Nammu, primordial, Mother goddess of creation, Origin of all.`,
   `Ereshkigal, queen, Goddess of the underworld, Guardian of the dead.`,
   `Nabu, god of scribes, Wisdom's messenger and scribe, Recording history.`,
   `Sin, moon god, serene, Glowing orb in night's embrace, Lunar deity.`,
   `Adad, storm god's might, Thunder, rain, and fertility, Nature's fierce power.`,
   `Tigris and Euphrates, Mesopotamia's lifeblood, Cradle of cultures.`,
   `Nineveh's great walls, Ashurbanipal's library, Assyrian knowledge.`,
   `Winged bull statues guard, Palace gates of ancient might, Assyrian power.`,
   `Assyrian archers, In battle, fearsome prowess, Conquerors of lands.`,
   `Nebuchadnezzar's reign, Hanging Gardens of Babylon, Mesopotamian dream.`,
   `Assyria's might, Warriors of fearless prowess, Empire's iron fist.`,
   `Nineveh's splendor, Assyrian capital's might, Lion hunts immortalized.`,
   `Ashurbanipal, Assyrian king and scholar, Library of wisdom.`,
   `Winged bull guardians, Assyrian palaces stand, Symbols of power.`,
   `Military might, Assyrian conquests unfold, Lands kneel in awe.`,
   `Ishtar Gate's grandeur, Blue-glazed bricks guard the city, Mesopotamian marvel.`,
   `Babylon's scholars, Astronomy's ancient lore, Tablets of wisdom.`,
   `Babylon's grand walls, Marduk's city rises high, Ancient wonder thrives.`,
   `Code of Hammurabi, Babylonian law unveiled, Justice carved in stone.`,
   `Ishtar's sacred gate, Babylonian goddess' realm, Love and war entwined.`,
   `Epic of Gilgamesh, Babylon's timeless tale of kings, Humanity's quest.`,
   `Ziggurats touch sky, Babylonian temples soar, Worshipers ascend.`,
   `Persian carpets weave, Colors of ancient tales, Artistry adorns.`,
   `Cyrus the Great's reign, Empire of tolerance, Achaemenid pride.`,
   `Persepolis stands, Palace of Persian kings, Splendor of the past.`,
   `Persia's splendor shines, Cultural tapestry weaves, Empire's vibrant heart.`,
   `Jerusalem's hill, Temple's sacred presence shines, Ancient spiritual.`,
   `Dead Sea Scrolls reveal, Hidden words of ancient times, Jewish heritage.`,
   `Masada's refuge, Fortress on the desert heights, Echoes of freedom.`,
   `Cedars of Lebanon, Phoenician ships set sail, Trade across the seas.`,
   `Purple dye's treasure, Tyrian textiles unfold, Phoenician arts thrive.`,
   `Carthage's grandeur, Phoenician city-state's might, Hannibal's bold march.`,
   `Phoenician shores, Sailing merchants forge new paths, Trade's ancient beacon.`,
   `Selucid kings rule, Hellenistic empire's grasp, Eastern lands embrace.`,
   `Ptolemaic clash, Seleucids and Egypt's might, Power struggles wage.`,
   `Antioch's grandeur, Selucid capital shines, Center of the realm.`,
   `Seleucid coins gleam, Numismatic legacy, Economic might.`,
   `Eastern conquests, Seleucid armies advance, Empire expands.`,
   `Seleucid culture, Greek influence takes hold, Eastern fusion blooms.`,
   `Hellenistic heirs, Seleucids' mixed heritage, East and West converge.`,
   `Bactrian treasure, Greek-Bactrian artistry, Selucid legacy.`,
   `Parthian uprising, Seleucids face resistance, Eastern power shift.`,
   `Seleucid decline, Internal strife weakens grip, Empire's final days.`,
   `Parthian horsemen, Mounted archers swift and skilled, Warriors of might.`,
   `Silk Road's gateway, Parthian Empire's trade flow, East and West unite.`,
   `Parthian splendor, Art and culture flourish bright, Golden age unfolds.`,
   `Parthian arrows, Deadly rain upon their foes, Battle's lethal dance.`,
   `Arsacid rule, Parthia's noble dynasty, Eastern power's flame.`,
];


