module.exports = [
   `Sacred funeral rites, Romans honor their loved ones, In eternal rest.`,
   `Tombstones stand in rows, Testimony to the past, Remembered in stone.`,
   `Mausoleums grand, Sheltering ancestral souls, Respect for the dead.`,
   `Cremation's embrace, Ashes scattered to the wind, Spirit finds its peace.`,
   `Funeral processions, Mourners clad in black attire, Sorrow fills the air.`,
   `Tombs carved in marble, Guarding secrets of the past, Silent sentinels.`,
   `Elegantly adorned, Sarcophagi of the elite, Preserving their legacy.`,
   `Underground chambers, Catacombs of the departed, Mysteries untold.`,
   `Tender funeral pyres, Embers dancing in the night, Souls ascend to stars.`,
   `Grave goods carefully placed, Offerings for the afterlife, Guiding spirits forth.`,
   `Inscribed epitaphs, Words of remembrance and love, Honoring the gone.`,
   `Columbaria stand, Homes for departed spirits, Peace in sacred walls.`,
   `Nestled in the stone, Rows of niches side by side, Resting souls find solace.`,
   `Dove-shaped openings, Columbaria's embrace, Symbol of peace reigns.`,
   `Whispering echoes, Columbarium's hallowed halls, Silent remembrance.`,
   `Columbaria's grace, Harboring memories dear, Eternity's embrace.`,
   `Rome's mighty embrace, Colosseum's grandeur stands, Empire's eternal.`,
   `Roman aqueducts, Engineering marvels stand, Water's ancient flow.`,
   `Augustus, first prince, Restorer of Rome's glory, Imperial dawn.`,
   `Nikopolis' pride, Monument of triumph stands, Echoes of valor.`,
   `The Colosseum stands, Arena of ancient might, Glory of Rome's past.`,
   `Pantheon's grand dome, Temple of gods, celestial, Architectural feat.`,
   `The Roman Forum, Heart of political life, Echoes of power.`,
   `Roman Colosseum, Gladiators' fierce battles, Crowds' thunderous roar.`,
   `Pompeii preserved, Volcanic ash froze in time, Roman life revealed.`,
   `Roman amphitheaters, Gladiators' fierce battles, Roars of ancient crowds.`,
   `Pompeii's ashes, Frozen city of the past, Time capsule revealed.`,
   `Rome's mighty empire, Engineering marvels stand, Legacy endures.`,
   `Ancient scrolls unroll, Herculaneum's buried texts, Lost knowledge revived.`,
   `Trajan's Column high, Carved tales of conquest and might, Emperor's triumph.`,
   `The Circus Maximus, Chariot races thunder, Crowds cheer with fervor.`,
   `The Arch of Constantine, Victory's eternal mark, Emperor's tribute.`,
   `The Forum of Trajan, Imperial grandeur displayed, Column and market.`,
   `The Arch of Titus, Symbol of triumph and spoils, Jerusalem's fall.`,
   `The Roman Pantheon, Divine architecture's grace, Gods' temple of awe.`,
   `The Temple of Saturn, Ancient deity revered, Guardian of wealth.`,
   `The Mausoleum, Hadrian's grand resting place, Imperial splendor.`,
   `The Theatre of Pompey, First stone theatre of Rome, Dramatic performances.`,
   `The Arch of Septimius, Monument of victory, Severan triumph.`,
   `The Temple of Vesta, Sacred flame forever lit, Goddess of hearth and home.`,
   `The Baths of Diocletian, Imperial bathing complex, Opulence in stone.`,
   `The Appian Way stretches, Ancient road's historic path, Echoes of travelers.`,
   `The Baths of Caracalla, Opulent indulgence, Ancient spa of leisure.`,
   `The Ara Pacis, Altar of peace and harmony, Augustan vision.`,
   `The Theatre of Marcellus, Entertainment's grand stage, Drama enchants all.`,
   `The Pont du Gard stands, Aqueduct's architectural feat, Water's life-giving flow.`,
   `Latin's ancient tongue, Echoes of Roman glory, Language of the past.`,
   `Latin's rhythmic flow, Melodies of ancient verse, Poetry's embrace.`,
   `Ovid, poet bold, Tales of metamorphosis, Artistry unleashed.`,
   `Vergil, epic's voice, Aeneid's hero's journey, Mastery of verse.`,
   `Horace, lyricist, Odes of wisdom and delight, Poetic finesse.`,
   `Propertius, love's bard, Passion's verses, heartfelt cries, Emotion's essence.`,
   `Ovid, tales unfold, Metamorphoses in verse, Myths transformed by words.`,
   `Vergil, epic strain, Aeneas' noble quest, Rome's founding tale told.`,
   `Horace, lyric grace, Odes sing of love and life, Wisdom in his lines.`,
   `Propertius, heart's muse, Passionate elegies soar, Love's pain finds release.`,
   `Satirical wit, Ennius and his plays mock, Society's flaws shown.`,
   `Plautus' wit and jest, Lively comedies unfold, Laughter fills the stage.`,
   `Terence, graceful words, Elegant plays, moral tales, Lessons wrapped in mirth.`,
   `Comic merriment, Roman theatre's delight, Laughs echo through time.`,
   `Poets of Rome's age, Words immortalize their fame, Literary gems.`,
   `Each, in their own right, Ancient Rome's poetic gems, Legacy endures.`,
   `Linguistic prowess, Latin's grammar and syntax, Mastery of words.`,
   `Latin, lingua franca, Intellectual bridge of minds, Scholars' common ground.`,
   `Latin's legacy, Root of Romance languages, Latin lives through time.`,
   `Ancient victory, Nikopolis remembers, Glory sealed in stone.`,
   `Nikopolis stands, Triumph's stone, immortalized, Victory proclaimed.`,
   `Eternal city, Rome's streets paved with history, Footsteps of the past.`,
   `Roman amphitheater, Coliseum's blood-stained sand, Gladiators' fate.`,
   `Herculaneum's ash, Buried stories of the past, Volcano's embrace.`,
   `Hadrian's grand wall, Roman empire's frontier, Ancient boundary.`,
   `Pompeii's lost souls, Frozen in Vesuvius' grasp, Eternal tableau.`,
   `Pompeii's ashes hide, Frozen moments of the past, Volcanic embrace.`,
   `Forum's bustling heart, Rome's pulse in ancient streets, Legends come alive.`,
   `Senate's noble hall, Republic's democratic voice, Rome's governing heart.`,
   `Caesar's mighty march, Legions conquer distant lands, Empire's expansion.`,
   `Cicero's silver tongue, Orator of Roman law, Republic's advocate.`,
   `Colosseum's roar, Gladiators face their fate, Crowds revel in blood.`,
   `Forum's bustling square, Citizens engage in trade, Heart of Roman life.`,
   `Vestal flames burn bright, Temple's sacred fire endures, Ancient Roman faith.`,
   `Roman aqueducts, Engineering marvels soar, Water's vital flow.`,
   `Julius' crossed Rubicon, Republic's fate sealed in blood, Caesar's mighty reign.`,
   `Boudica, queen, Warrior woman, rebel soul, Roman rule defied.`,
   `Roman road network, Paths connect the vast empire, Trade and unity.`,
   `Pax Romana's peace, Empire's golden age unfolds, Stability's reign.`,
   `Augustus, first prince, Pax Romana's architect, Empire finds peace.`,
   `Caesar's heir ascends, Augustus, Rome's revered one, Imperator's might.`,
   `Augustan Age dawns, Cultural renaissance blooms, Golden era thrives.`,
   `Res Gestae proclaims, Augustus' deeds and triumphs, His legacy told.`,
   `Augustus' Rome stands, Majestic city of marble, Imperial vision.`,
   `Cleopatra's child, Selene, queen of new lands, Egypt's royal blood.`,
   `Merged in Roman chains, Selene finds strength and grace, Proud Cleopatra's heir.`,
   `In Claudian court, Agrippina's shrewd counsel, Imperial power.`,
   `Agrippina's strength, Augusta, noble matron, Matriarch revered.`,
   `Constantine's embrace, Ancient Christianity's rise, Church and empire unite.`,
   `Constantine, the Great, Roman emperor, Christian, Faith shapes his empire.`,
   `Helena, his mother, Empress of Christian heart, Uncovering relics.`,
   `Edict of Milan, Constantine's decree of peace, Christianity thrives.`,
   `Helena's pilgrimage, Holy Land's sacred treasures found, Cross of Christ revealed.`,
   `Constantinople, City named after the Great, Christian stronghold.`,
   `Mother of the throne, Agrippina's influence, Dynasty's linchpin.`,
   `Agrippina's might, Empress of the Roman realm, Ambition drives her.`,
   `Fulvia, fierce spirit, Political prowess blooms, Power in her hands.`,
   `Mistress of intrigue, Fulvia's ambition shines, A force to reckon.`,
   `Lucretia's virtue, Rome's tragic tale unfolds, Purity stained red.`,
   `Beauty and sorrow, Lucretia, symbol of honor, Chaste spirit avenged.`,
   `Cleopatra's end, Selene carries her legacy, Egypt's last princess.`,
   `Selene's rule shines, Queen of Mauretania, Ancient power embraced.`,
   `Silent whispers echo, Cleopatra Selene's tale, Noble lineage fades.`,
   `Julia's marriages, Political alliances, Dynastic web weaves.`,
   `Exiled in sorrow, Julia's fate, her father's hand, Fall from grace, lost love.`,
   `Julia's legacy, Tainted by her tumultuous life, Augustan tragedy.`,
   `Scandal stains her name, Julia's wild spirit tamed, Constrained by her birth.`,
   `Julia, imperial, Raised to bear Rome's burden, Her life, a mosaic.`,
   `Julia's light fades, Shadowed by her family's strife, Tragic princess' tale.`,
   `Pax Romana's dawn, First Emperor's golden age, Rome's foundation laid.`,
   `Augustus' heir, Guarded Rome with somber might, Shadowed reign endured.`,
   `Madness gripped his mind, Tyranny and excess reigned, Rome's dark chapter told.`,
   `Scholar on the throne, Brought stability to Rome, Empire's wisdom found.`,
   `Violent and cruel, Fire consumed Rome's grandeur, Emperor's downfall.`,
   `Short-lived reign of strife, Rome's year of four emperors, Power changing hands.`,
   `Brief and tragic rule, Power slipped through his fingers, Emperor's tragic end.`,
   `Gluttonous excess, Indulgence marked his short reign, Rome's feast turned to famine.`,
   `Builder of the Flavians, Colosseum's grandeur rose, Empire restored.`,
   `Mount Vesuvius, Pompeii's fiery demise, Emperor's sorrow felt.`,
   `Authoritarian, Rome's fierce protector and foe, Empire's dark shadows.`,
   `Adopted heir's reign, Justice and reforms pursued, Rome's wise statesman led.`,
   `Expansion's might, Empire reached its zenith, Rome's golden era.`,
   `Builder of the Wall, Vast travels and grand projects, Rome's boundaries shaped.`,
   `Peaceful rule endured, Prosperity embraced Rome, Empire's gentle hand.`,
   `Stoic philosopher, Wise emperor in trying times, Rome's guiding light shone.`,
   `Gladiator prince, Madness tainted his reign's end, Rome's decline began.`,
   `Short-lived reign of virtue, Assassination's cruel blow, Emperor's fleeting hope.`,
   `Purchased empire's throne, Rome's auctioned sovereignty, Emperor's shame proclaimed.`,
   `African conqueror, Military might restored, Rome's strength regained.`,
   `Citizenship granted, Rome's subjects united, Emperor's bloody hand.`,
   `Assassination's plot, Short-lived rule of fear and doubt, Rome's betrayal felt.`,
   `Eastern influence, Religious chaos unleashed, Emperor's scandalous reign.`,
   `Youthful emperor, Scholar and peacekeeper's aim, Rome's final hope.`,
   `Barbarian's ascent, Military might embraced, Rome's new emperor.`,
   `Fierce Gothic victory, Restored Rome's military might, Emperor's triumph hailed.`,
   `Eastern origins, Empire's first non-Roman, Rome's multicultural.`,
   `Persecutor's reign, Christianity faced trial, Rome's faith tested.`,
   `Persian captivity, Emperor enslaved in war, Rome's humiliation.`,
   `Division's burden, Usurpers challenged his rule, Rome's empire frayed.`,
   `Elder statesman's reign, Historian on the throne, Rome's brief respite found.`,
   `Military might, Empire's borders defended, Rome's strength in his hands.`,
   `Persian campaign, Emperor's sudden death claimed, Rome's power cut short.`,
   `Rome's usurper's call, Bridge of Milvian's decisive, Emperor's fall proclaimed.`,
   `Conversion's embrace, Rome's capital shifted east, Emperor's Christian reign.`,
   `Constantine's son, Troubled reign marred by strife, Rome's decline progressed.`,
   `Eastern emperor, Religious controversies, Rome's empire divided.`,
   `Pagan emperor, Restoration of old ways, Rome's last gasp of faith.`,
   `Short-lived reign's end, Retreat from Persian Empire, Rome's surrender felt.`,
   `West's strong defender, Empire's struggles faced head-on, Rome's stability sought.`,
   `Eastern empire's grasp, Gothic catastrophe loomed, Rome's disaster near.`,
   `Youthful emperor, Christianity's stronghold, Rome's faith proclaimed.`,
   `Child on the throne, Guarded by regents' hands, Rome's puppet ruler.`,
   `Christian empire's end, Division of east and west, Rome's final chapter.`,
   `Eastern empire's rule, Weakness and decline set in, Rome's fading light.`,
   `West's troubled reign, Visigothic sack of Rome, Empire's final fall.`,
   `Last emperor's name, End of Western Roman rule, Rome's legacy fades.`,
   `Res Gestae inscribed, Augustus' deeds proclaimed loud, Empire's founding tale.`,
   `Words of Augustus, Res Gestae tells his story, Legacy written.`,



];


